version: '3'

services: 
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    #env_file:
    #  - 'env.influxdb'
    #volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      #- /srv/docker/influxdb/data:/var/lib/influxdb
  chronograf:
    image: chronograf:latest
    #volumes:
      # Mount for chronograf database
      #- ./chronograf/data/:/var/lib/chronograf/
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "8888:8888"
    depends_on:
      - influxdb
